name: KotlinLoader
main: dev.steyn.kotlinloader.bootstrap.KotlinLoaderPlugin
version: ${project.version}
api-version: 1.13
load: STARTUP
author: steenooo

commands:
  kotlinloader:
    aliases: [kotlin, kotlinl, kl]
    description: Kotlin Loader Plugin Information
    permission: kotlinloader.info
    usage: /kotlinloader