name: KotlinLoader
main: dev.steyn.kotlinloader.plugin.KotlinLoader
version: ${project.version}
api-version: 1.13
load: STARTUP

commands:
  kotlinloader:
    aliases: [kotlin, kotlinl, kl]
    description: Kotlin Loader Plugin Information
    permission: kotlinloader.info
    usage: /kotlinloader